//! Fast HashMap and HashSet for TypeId and ComponentId keys.
//!
//! TypeId is already a unique identifier generated by the compiler,
//! so we can skip the hash computation and use its bits directly.
//! ComponentId wraps TypeId, so it benefits from the same optimization.
//!
//! This is an internal module - these types are used internally by nimbus_ecs.

use hashbrown::{HashMap, HashSet};
use std::any::TypeId;
use std::hash::{BuildHasher, Hasher};
use crate::component::ComponentId;

// ============================================================================
// Identity Hasher for TypeId
// ============================================================================

/// A hasher that assumes the input is already well-distributed (like TypeId).
/// Since TypeId is a unique identifier generated by the compiler, we can
/// skip the hash computation and use its bits directly.
#[derive(Default)]
pub struct TypeIdHasher(u64);

impl Hasher for TypeIdHasher {
    #[inline]
    fn write(&mut self, bytes: &[u8]) {
        // TypeId is 8 or 16 bytes depending on platform
        // Just use the first 8 bytes as the hash
        debug_assert!(bytes.len() >= 8);
        self.0 = u64::from_ne_bytes(bytes[..8].try_into().unwrap());
    }

    #[inline]
    fn write_u64(&mut self, n: u64) {
        self.0 = n;
    }

    #[inline]
    fn finish(&self) -> u64 {
        self.0
    }
}

/// BuildHasher for TypeIdHasher.
#[derive(Default, Clone)]
pub struct TypeIdBuildHasher;

impl BuildHasher for TypeIdBuildHasher {
    type Hasher = TypeIdHasher;

    #[inline]
    fn build_hasher(&self) -> Self::Hasher {
        TypeIdHasher(0)
    }
}

// ============================================================================
// Type aliases for fast TypeId collections
// ============================================================================

/// Fast HashSet for TypeId keys using identity hasher.
/// O(1) lookups without redundant hashing.
pub type TypeHashSet = HashSet<TypeId, TypeIdBuildHasher>;

/// Fast HashMap for TypeId keys using identity hasher.
/// O(1) lookups without redundant hashing.
pub type TypeHashMap<V> = HashMap<TypeId, V, TypeIdBuildHasher>;

/// Fast HashSet for ComponentId keys using identity hasher.
/// O(1) lookups without redundant hashing.
pub type ComponentIdHashSet = HashSet<ComponentId, TypeIdBuildHasher>;

/// Fast HashMap for ComponentId keys using identity hasher.
/// O(1) lookups without redundant hashing.
pub type ComponentIdHashMap<V> = HashMap<ComponentId, V, TypeIdBuildHasher>;

#[cfg(test)]
mod tests {
    use super::*;

    struct TestTypeA;
    struct TestTypeB;

    #[test]
    fn type_hash_set_works() {
        let mut set = TypeHashSet::default();
        set.insert(TypeId::of::<TestTypeA>());
        set.insert(TypeId::of::<TestTypeB>());

        assert!(set.contains(&TypeId::of::<TestTypeA>()));
        assert!(set.contains(&TypeId::of::<TestTypeB>()));
        assert!(!set.contains(&TypeId::of::<String>()));
        assert_eq!(set.len(), 2);
    }

    #[test]
    fn type_hash_map_works() {
        let mut map: TypeHashMap<&str> = TypeHashMap::default();
        map.insert(TypeId::of::<TestTypeA>(), "type_a");
        map.insert(TypeId::of::<TestTypeB>(), "type_b");

        assert_eq!(map.get(&TypeId::of::<TestTypeA>()), Some(&"type_a"));
        assert_eq!(map.get(&TypeId::of::<TestTypeB>()), Some(&"type_b"));
        assert_eq!(map.get(&TypeId::of::<String>()), None);
    }
}

